"""
Pydantic schema definitions for Gemini 2.5 Flash structured output.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class GeminiConstructionReport(BaseModel):
    """Structured Construction Intelligence Report generated by Gemini 2.5 Flash."""
    overall_status: str = Field(
        description="Current overall project status (e.g. Optimal, Good, Needs Attention, Critical)"
    )
    executive_summary: str = Field(
        description="High-level narrative summary of project operational status and key intelligence insights"
    )
    key_findings: List[str] = Field(
        description="List of primary operational observations grounded in ML results and site measurements"
    )
    critical_alerts: List[str] = Field(
        description="High-priority safety, machinery, material, or schedule concerns requiring immediate focus"
    )
    risk_explanation: str = Field(
        description="Plain-language explanation of the predicted risk score and underlying risk factors"
    )
    performance_explanation: str = Field(
        description="Explanation of the predicted performance level and contributing operational features"
    )
    cost_explanation: str = Field(
        description="Explanation of forecasted cost deviation and budget status"
    )
    schedule_explanation: str = Field(
        description="Explanation of forecasted schedule deviation and timeline status"
    )
    optimization_explanation: str = Field(
        description="Contextual explanation of the recommended optimization suggestion and supporting factors"
    )
    recommended_actions: List[str] = Field(
        description="Prioritized, practical next actions for project managers and site engineers"
    )
    priority: str = Field(
        description="Overall priority level (Low, Medium, High, Critical)"
    )
    confidence_note: str = Field(
        description="Statement detailing data bounds, model confidence, and operational limitations"
    )


class SpacePriorityItem(BaseModel):
    zone: str = Field(description="Operational site zone name")
    priority: str = Field(description="Priority level: LOW, MEDIUM, HIGH, CRITICAL")
    reason: str = Field(description="Operational rationale for priority level")


class RecommendedActionItem(BaseModel):
    action: str = Field(description="Actionable site space modification recommendation")
    priority: str = Field(description="Action priority level: LOW, MEDIUM, HIGH, CRITICAL")
    reason: str = Field(description="Operational justification for recommended action")


class GeminiSpaceReport(BaseModel):
    """Structured Space Intelligence Report generated by Gemini 2.5 Flash."""
    summary: str = Field(description="High-level narrative summary of space allocation and layout efficiency")
    layout_explanation: str = Field(description="Plain-language explanation of why specific zone areas were chosen")
    key_findings: List[str] = Field(description="List of primary spatial observations grounded in SciPy optimization results")
    space_priorities: List[SpacePriorityItem] = Field(description="Zone-by-zone allocation priorities")
    recommended_actions: List[RecommendedActionItem] = Field(description="Prioritized site layout adjustments for engineers")
    safety_considerations: List[str] = Field(description="Safety buffer and emergency access observations")
    optimization_assumptions: List[str] = Field(description="Underlying assumptions used in space demand calculation")
    limitations: List[str] = Field(description="Operational boundary limits and disclaimer regarding engineering signoff")


class GeminiReportWrapper(BaseModel):
    """Wrapper response model accommodating active reports and fallback states."""
    status: str = Field(default="success", description="Status of AI report generation: success or unavailable")
    message: Optional[str] = Field(default=None, description="Detailed message when unavailable or cached")
    report: Optional[GeminiConstructionReport] = Field(default=None, description="Structured construction report")
    space_report: Optional[GeminiSpaceReport] = Field(default=None, description="Structured space report")

