import React, { useState, useEffect } from 'react';
import { fetchAlerts } from '../services/api';

export const AlertCenter: React.FC = () => {
  const [alerts, setAlerts] = useState<any[]>([]);

  const defaultAlerts = [
    {
      id: 'alt-01',
      severity: 'CRITICAL',
      type: 'SAFETY ALERT',
      title: 'Safety Incidents Exceeded Threshold',
      timestamp: '12:02:14',
      trigger: 'Safety incidents count exceeded mandatory limit.',
      currentValue: '2 incidents',
      threshold: '0',
      action: 'Review site safety conditions immediately.'
    },
    {
      id: 'alt-02',
      severity: 'HIGH',
      type: 'CRITICAL RISK',
      title: 'Risk Score Above Critical Limit',
      timestamp: '12:02:14',
      trigger: 'Linear regression risk score crossed 70%.',
      currentValue: '72%',
      threshold: '70%',
      action: 'Reallocate machinery and workers to mitigate hazard.'
    },
    {
      id: 'alt-03',
      severity: 'HIGH',
      type: 'SCHEDULE DELAY',
      title: 'Schedule Deviation Exceeds Threshold',
      timestamp: '12:00:02',
      trigger: 'Time forecast deviation is +4.8 days.',
      currentValue: '+4.8 days',
      threshold: '+0 days',
      action: 'Inspect lagging task progress on structural phase.'
    },
    {
      id: 'alt-04',
      severity: 'MEDIUM',
      type: 'MATERIAL SHORTAGE',
      title: 'Material Inventory Shortage Warning',
      timestamp: '11:58:12',
      trigger: 'Daily material usage exceeds replenishment rate.',
      currentValue: 'ALERT',
      threshold: '0',
      action: 'Re-order steel rebar and cement deliveries.'
    },
    {
      id: 'alt-05',
      severity: 'MEDIUM',
      type: 'COST WARNING',
      title: 'Cost Deviation Exceeds Warning Limit',
      timestamp: '11:54:27',
      trigger: 'XGBoost cost forecast indicates budget overrun.',
      currentValue: '+$8,420',
      threshold: '+$5,000',
      action: 'Review equipment rental overtime rates.'
    },
    {
      id: 'alt-06',
      severity: 'LOW',
      type: 'EQUIPMENT WARNING',
      title: 'Machinery Vibration Spike Observed',
      timestamp: '11:52:01',
      trigger: 'Sensor 12 reported 28.6 mm/s vibration.',
      currentValue: '28.6 mm/s',
      threshold: '25.0 mm/s',
      action: 'Perform maintenance check on excavator pump.'
    },
    {
      id: 'alt-07',
      severity: 'INFO',
      type: 'RESOURCE PRESSURE',
      title: 'High Worker-to-Task Ratio Detected',
      timestamp: '11:50:20',
      trigger: '74 workers assigned to active tasks.',
      currentValue: '74 workers',
      threshold: '60 workers',
      action: 'Consider shifting workers to finishing tasks.'
    }
  ];

  useEffect(() => {
    fetchAlerts()
      .then(data => {
        if (data && data.length > 0) setAlerts(data);
        else setAlerts(defaultAlerts);
      })
      .catch(() => setAlerts(defaultAlerts));
  }, []);

  const getAlertCardStyle = (severity: string) => {
    switch (severity) {
      case 'CRITICAL':
        return { backgroundColor: '#111111', color: '#FFFFFF', border: '2px solid #111111' };
      case 'HIGH':
        return { backgroundColor: '#fff7ed', color: '#111111', border: '2px solid #f97316' };
      case 'MEDIUM':
        return { backgroundColor: '#E4FF5B', color: '#111111', border: '2px solid #111111' };
      case 'LOW':
        return { backgroundColor: '#4FC3F7', color: '#111111', border: '2px solid #111111' };
      case 'INFO':
      default:
        return { backgroundColor: '#F5F3E3', color: '#111111', border: '2px solid #111111' };
    }
  };

  return (
    <div style={{ maxWidth: '1400px', margin: '0 auto', padding: '16px 24px 48px 24px' }}>
      {/* Header */}
      <div style={{ marginBottom: '24px', borderBottom: '2px solid #111111', paddingBottom: '16px' }}>
        <h1 style={{ fontFamily: 'Anton, sans-serif', fontSize: '48px', color: '#111111', textTransform: 'uppercase' }}>
          ALERTS
        </h1>
        <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '14px', color: '#555555' }}>
          Signals that require attention. Generated by deterministic rules. Independent of Gemini.
        </p>
      </div>

      {/* Alert Feed List */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
        {alerts.map(item => {
          const style = getAlertCardStyle(item.severity);
          return (
            <div
              key={item.id}
              style={{
                ...style,
                borderRadius: '12px',
                padding: '20px 24px',
                boxShadow: '0 4px 10px rgba(0,0,0,0.04)'
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                  <span style={{
                    fontSize: '11px',
                    fontFamily: 'JetBrains Mono, monospace',
                    fontWeight: '800',
                    padding: '2px 8px',
                    borderRadius: '4px',
                    backgroundColor: item.severity === 'CRITICAL' ? '#FFFFFF' : '#111111',
                    color: item.severity === 'CRITICAL' ? '#111111' : '#FFFFFF'
                  }}>
                    {item.severity}
                  </span>
                  <span style={{ fontSize: '12px', fontFamily: 'JetBrains Mono, monospace', fontWeight: 'bold' }}>
                    {item.type}
                  </span>
                </div>
                <span style={{ fontSize: '11px', fontFamily: 'JetBrains Mono, monospace' }}>
                  {item.timestamp}
                </span>
              </div>

              <h3 style={{ fontFamily: 'Anton, sans-serif', fontSize: '20px', textTransform: 'uppercase', marginBottom: '6px' }}>
                {item.title}
              </h3>

              <p style={{ fontSize: '13px', fontFamily: 'Inter, sans-serif', marginBottom: '12px', opacity: 0.9 }}>
                {item.trigger || item.description}
              </p>

              <div style={{ display: 'flex', gap: '24px', fontSize: '12px', fontFamily: 'JetBrains Mono, monospace', borderTop: '1px solid rgba(0,0,0,0.15)', paddingTop: '10px' }}>
                <span><strong>Current:</strong> {item.currentValue || 'Alert'}</span>
                <span><strong>Threshold:</strong> {item.threshold || 'Configured Limit'}</span>
                <span><strong>Action:</strong> {item.action || 'Inspect conditions'}</span>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
